name: Publish Docker image
on:
  push:
      # Sequence of patterns matched against refs/heads
      branches:    
        # Push events on main branch
        - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: toyz/uwu-server/uwu
          tag_with_ref: true
